//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace led_rear.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="file_uploadSoap", Namespace="http://tempuri.org/")]
    public partial class file_upload : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback AppendOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback files_nameOperationCompleted;
        
        private System.Threading.SendOrPostCallback screenfiles_nameOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_fileOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_screenfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadScreenOperationCompleted;
        
        private System.Threading.SendOrPostCallback submit_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback files_sizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Access_findAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback Access_findOperationCompleted;
        
        private System.Threading.SendOrPostCallback Access_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Access_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback Access_deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Access_ExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback channels_idOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public file_upload() {
            this.Url = global::led_rear.Properties.Settings.Default.led_rear_WebReference_file_upload;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CreateFileCompletedEventHandler CreateFileCompleted;
        
        /// <remarks/>
        public event AppendCompletedEventHandler AppendCompleted;
        
        /// <remarks/>
        public event VerifyCompletedEventHandler VerifyCompleted;
        
        /// <remarks/>
        public event files_nameCompletedEventHandler files_nameCompleted;
        
        /// <remarks/>
        public event screenfiles_nameCompletedEventHandler screenfiles_nameCompleted;
        
        /// <remarks/>
        public event delete_fileCompletedEventHandler delete_fileCompleted;
        
        /// <remarks/>
        public event delete_screenfileCompletedEventHandler delete_screenfileCompleted;
        
        /// <remarks/>
        public event DownloadFileCompletedEventHandler DownloadFileCompleted;
        
        /// <remarks/>
        public event DownloadScreenCompletedEventHandler DownloadScreenCompleted;
        
        /// <remarks/>
        public event submit_listCompletedEventHandler submit_listCompleted;
        
        /// <remarks/>
        public event files_sizeCompletedEventHandler files_sizeCompleted;
        
        /// <remarks/>
        public event Access_findAllCompletedEventHandler Access_findAllCompleted;
        
        /// <remarks/>
        public event Access_findCompletedEventHandler Access_findCompleted;
        
        /// <remarks/>
        public event Access_updateCompletedEventHandler Access_updateCompleted;
        
        /// <remarks/>
        public event Access_insertCompletedEventHandler Access_insertCompleted;
        
        /// <remarks/>
        public event Access_deleteCompletedEventHandler Access_deleteCompleted;
        
        /// <remarks/>
        public event Access_ExistCompletedEventHandler Access_ExistCompleted;
        
        /// <remarks/>
        public event channels_idCompletedEventHandler channels_idCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateFile(string fileName) {
            object[] results = this.Invoke("CreateFile", new object[] {
                        fileName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateFileAsync(string fileName) {
            this.CreateFileAsync(fileName, null);
        }
        
        /// <remarks/>
        public void CreateFileAsync(string fileName, object userState) {
            if ((this.CreateFileOperationCompleted == null)) {
                this.CreateFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateFileOperationCompleted);
            }
            this.InvokeAsync("CreateFile", new object[] {
                        fileName}, this.CreateFileOperationCompleted, userState);
        }
        
        private void OnCreateFileOperationCompleted(object arg) {
            if ((this.CreateFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateFileCompleted(this, new CreateFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Append", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Append(string fileName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] buffer, bool flag) {
            object[] results = this.Invoke("Append", new object[] {
                        fileName,
                        buffer,
                        flag});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AppendAsync(string fileName, byte[] buffer, bool flag) {
            this.AppendAsync(fileName, buffer, flag, null);
        }
        
        /// <remarks/>
        public void AppendAsync(string fileName, byte[] buffer, bool flag, object userState) {
            if ((this.AppendOperationCompleted == null)) {
                this.AppendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppendOperationCompleted);
            }
            this.InvokeAsync("Append", new object[] {
                        fileName,
                        buffer,
                        flag}, this.AppendOperationCompleted, userState);
        }
        
        private void OnAppendOperationCompleted(object arg) {
            if ((this.AppendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppendCompleted(this, new AppendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Verify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Verify(string fileName, string md5, bool flag) {
            object[] results = this.Invoke("Verify", new object[] {
                        fileName,
                        md5,
                        flag});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAsync(string fileName, string md5, bool flag) {
            this.VerifyAsync(fileName, md5, flag, null);
        }
        
        /// <remarks/>
        public void VerifyAsync(string fileName, string md5, bool flag, object userState) {
            if ((this.VerifyOperationCompleted == null)) {
                this.VerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyOperationCompleted);
            }
            this.InvokeAsync("Verify", new object[] {
                        fileName,
                        md5,
                        flag}, this.VerifyOperationCompleted, userState);
        }
        
        private void OnVerifyOperationCompleted(object arg) {
            if ((this.VerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyCompleted(this, new VerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/files_name", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] files_name() {
            object[] results = this.Invoke("files_name", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void files_nameAsync() {
            this.files_nameAsync(null);
        }
        
        /// <remarks/>
        public void files_nameAsync(object userState) {
            if ((this.files_nameOperationCompleted == null)) {
                this.files_nameOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfiles_nameOperationCompleted);
            }
            this.InvokeAsync("files_name", new object[0], this.files_nameOperationCompleted, userState);
        }
        
        private void Onfiles_nameOperationCompleted(object arg) {
            if ((this.files_nameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.files_nameCompleted(this, new files_nameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/screenfiles_name", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] screenfiles_name() {
            object[] results = this.Invoke("screenfiles_name", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void screenfiles_nameAsync() {
            this.screenfiles_nameAsync(null);
        }
        
        /// <remarks/>
        public void screenfiles_nameAsync(object userState) {
            if ((this.screenfiles_nameOperationCompleted == null)) {
                this.screenfiles_nameOperationCompleted = new System.Threading.SendOrPostCallback(this.Onscreenfiles_nameOperationCompleted);
            }
            this.InvokeAsync("screenfiles_name", new object[0], this.screenfiles_nameOperationCompleted, userState);
        }
        
        private void Onscreenfiles_nameOperationCompleted(object arg) {
            if ((this.screenfiles_nameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.screenfiles_nameCompleted(this, new screenfiles_nameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delete_file", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string delete_file(string file_name) {
            object[] results = this.Invoke("delete_file", new object[] {
                        file_name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delete_fileAsync(string file_name) {
            this.delete_fileAsync(file_name, null);
        }
        
        /// <remarks/>
        public void delete_fileAsync(string file_name, object userState) {
            if ((this.delete_fileOperationCompleted == null)) {
                this.delete_fileOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_fileOperationCompleted);
            }
            this.InvokeAsync("delete_file", new object[] {
                        file_name}, this.delete_fileOperationCompleted, userState);
        }
        
        private void Ondelete_fileOperationCompleted(object arg) {
            if ((this.delete_fileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_fileCompleted(this, new delete_fileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delete_screenfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string delete_screenfile(string file_name) {
            object[] results = this.Invoke("delete_screenfile", new object[] {
                        file_name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delete_screenfileAsync(string file_name) {
            this.delete_screenfileAsync(file_name, null);
        }
        
        /// <remarks/>
        public void delete_screenfileAsync(string file_name, object userState) {
            if ((this.delete_screenfileOperationCompleted == null)) {
                this.delete_screenfileOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_screenfileOperationCompleted);
            }
            this.InvokeAsync("delete_screenfile", new object[] {
                        file_name}, this.delete_screenfileOperationCompleted, userState);
        }
        
        private void Ondelete_screenfileOperationCompleted(object arg) {
            if ((this.delete_screenfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_screenfileCompleted(this, new delete_screenfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadFile(string file_name) {
            object[] results = this.Invoke("DownloadFile", new object[] {
                        file_name});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadFileAsync(string file_name) {
            this.DownloadFileAsync(file_name, null);
        }
        
        /// <remarks/>
        public void DownloadFileAsync(string file_name, object userState) {
            if ((this.DownloadFileOperationCompleted == null)) {
                this.DownloadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadFileOperationCompleted);
            }
            this.InvokeAsync("DownloadFile", new object[] {
                        file_name}, this.DownloadFileOperationCompleted, userState);
        }
        
        private void OnDownloadFileOperationCompleted(object arg) {
            if ((this.DownloadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadFileCompleted(this, new DownloadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadScreen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadScreen(string file_name) {
            object[] results = this.Invoke("DownloadScreen", new object[] {
                        file_name});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadScreenAsync(string file_name) {
            this.DownloadScreenAsync(file_name, null);
        }
        
        /// <remarks/>
        public void DownloadScreenAsync(string file_name, object userState) {
            if ((this.DownloadScreenOperationCompleted == null)) {
                this.DownloadScreenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadScreenOperationCompleted);
            }
            this.InvokeAsync("DownloadScreen", new object[] {
                        file_name}, this.DownloadScreenOperationCompleted, userState);
        }
        
        private void OnDownloadScreenOperationCompleted(object arg) {
            if ((this.DownloadScreenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadScreenCompleted(this, new DownloadScreenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/submit_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string submit_list(string listname) {
            object[] results = this.Invoke("submit_list", new object[] {
                        listname});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void submit_listAsync(string listname) {
            this.submit_listAsync(listname, null);
        }
        
        /// <remarks/>
        public void submit_listAsync(string listname, object userState) {
            if ((this.submit_listOperationCompleted == null)) {
                this.submit_listOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsubmit_listOperationCompleted);
            }
            this.InvokeAsync("submit_list", new object[] {
                        listname}, this.submit_listOperationCompleted, userState);
        }
        
        private void Onsubmit_listOperationCompleted(object arg) {
            if ((this.submit_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submit_listCompleted(this, new submit_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/files_size", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] files_size() {
            object[] results = this.Invoke("files_size", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void files_sizeAsync() {
            this.files_sizeAsync(null);
        }
        
        /// <remarks/>
        public void files_sizeAsync(object userState) {
            if ((this.files_sizeOperationCompleted == null)) {
                this.files_sizeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfiles_sizeOperationCompleted);
            }
            this.InvokeAsync("files_size", new object[0], this.files_sizeOperationCompleted, userState);
        }
        
        private void Onfiles_sizeOperationCompleted(object arg) {
            if ((this.files_sizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.files_sizeCompleted(this, new files_sizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Access_findAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Access_findAll(string sql, string table) {
            object[] results = this.Invoke("Access_findAll", new object[] {
                        sql,
                        table});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Access_findAllAsync(string sql, string table) {
            this.Access_findAllAsync(sql, table, null);
        }
        
        /// <remarks/>
        public void Access_findAllAsync(string sql, string table, object userState) {
            if ((this.Access_findAllOperationCompleted == null)) {
                this.Access_findAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccess_findAllOperationCompleted);
            }
            this.InvokeAsync("Access_findAll", new object[] {
                        sql,
                        table}, this.Access_findAllOperationCompleted, userState);
        }
        
        private void OnAccess_findAllOperationCompleted(object arg) {
            if ((this.Access_findAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Access_findAllCompleted(this, new Access_findAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Access_find", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Access_find(string sql) {
            object[] results = this.Invoke("Access_find", new object[] {
                        sql});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Access_findAsync(string sql) {
            this.Access_findAsync(sql, null);
        }
        
        /// <remarks/>
        public void Access_findAsync(string sql, object userState) {
            if ((this.Access_findOperationCompleted == null)) {
                this.Access_findOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccess_findOperationCompleted);
            }
            this.InvokeAsync("Access_find", new object[] {
                        sql}, this.Access_findOperationCompleted, userState);
        }
        
        private void OnAccess_findOperationCompleted(object arg) {
            if ((this.Access_findCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Access_findCompleted(this, new Access_findCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Access_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Access_update(string sql) {
            object[] results = this.Invoke("Access_update", new object[] {
                        sql});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Access_updateAsync(string sql) {
            this.Access_updateAsync(sql, null);
        }
        
        /// <remarks/>
        public void Access_updateAsync(string sql, object userState) {
            if ((this.Access_updateOperationCompleted == null)) {
                this.Access_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccess_updateOperationCompleted);
            }
            this.InvokeAsync("Access_update", new object[] {
                        sql}, this.Access_updateOperationCompleted, userState);
        }
        
        private void OnAccess_updateOperationCompleted(object arg) {
            if ((this.Access_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Access_updateCompleted(this, new Access_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Access_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Access_insert(string sql) {
            this.Invoke("Access_insert", new object[] {
                        sql});
        }
        
        /// <remarks/>
        public void Access_insertAsync(string sql) {
            this.Access_insertAsync(sql, null);
        }
        
        /// <remarks/>
        public void Access_insertAsync(string sql, object userState) {
            if ((this.Access_insertOperationCompleted == null)) {
                this.Access_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccess_insertOperationCompleted);
            }
            this.InvokeAsync("Access_insert", new object[] {
                        sql}, this.Access_insertOperationCompleted, userState);
        }
        
        private void OnAccess_insertOperationCompleted(object arg) {
            if ((this.Access_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Access_insertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Access_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Access_delete(string sql) {
            object[] results = this.Invoke("Access_delete", new object[] {
                        sql});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Access_deleteAsync(string sql) {
            this.Access_deleteAsync(sql, null);
        }
        
        /// <remarks/>
        public void Access_deleteAsync(string sql, object userState) {
            if ((this.Access_deleteOperationCompleted == null)) {
                this.Access_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccess_deleteOperationCompleted);
            }
            this.InvokeAsync("Access_delete", new object[] {
                        sql}, this.Access_deleteOperationCompleted, userState);
        }
        
        private void OnAccess_deleteOperationCompleted(object arg) {
            if ((this.Access_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Access_deleteCompleted(this, new Access_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Access_Exist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Access_Exist(string sql) {
            object[] results = this.Invoke("Access_Exist", new object[] {
                        sql});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Access_ExistAsync(string sql) {
            this.Access_ExistAsync(sql, null);
        }
        
        /// <remarks/>
        public void Access_ExistAsync(string sql, object userState) {
            if ((this.Access_ExistOperationCompleted == null)) {
                this.Access_ExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccess_ExistOperationCompleted);
            }
            this.InvokeAsync("Access_Exist", new object[] {
                        sql}, this.Access_ExistOperationCompleted, userState);
        }
        
        private void OnAccess_ExistOperationCompleted(object arg) {
            if ((this.Access_ExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Access_ExistCompleted(this, new Access_ExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/channels_id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string channels_id() {
            object[] results = this.Invoke("channels_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void channels_idAsync() {
            this.channels_idAsync(null);
        }
        
        /// <remarks/>
        public void channels_idAsync(object userState) {
            if ((this.channels_idOperationCompleted == null)) {
                this.channels_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onchannels_idOperationCompleted);
            }
            this.InvokeAsync("channels_id", new object[0], this.channels_idOperationCompleted, userState);
        }
        
        private void Onchannels_idOperationCompleted(object arg) {
            if ((this.channels_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.channels_idCompleted(this, new channels_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreateFileCompletedEventHandler(object sender, CreateFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AppendCompletedEventHandler(object sender, AppendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AppendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void VerifyCompletedEventHandler(object sender, VerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void files_nameCompletedEventHandler(object sender, files_nameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class files_nameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal files_nameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void screenfiles_nameCompletedEventHandler(object sender, screenfiles_nameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class screenfiles_nameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal screenfiles_nameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void delete_fileCompletedEventHandler(object sender, delete_fileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_fileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_fileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void delete_screenfileCompletedEventHandler(object sender, delete_screenfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_screenfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_screenfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DownloadFileCompletedEventHandler(object sender, DownloadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DownloadScreenCompletedEventHandler(object sender, DownloadScreenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadScreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadScreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void submit_listCompletedEventHandler(object sender, submit_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submit_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submit_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void files_sizeCompletedEventHandler(object sender, files_sizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class files_sizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal files_sizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Access_findAllCompletedEventHandler(object sender, Access_findAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Access_findAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Access_findAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Access_findCompletedEventHandler(object sender, Access_findCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Access_findCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Access_findCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Access_updateCompletedEventHandler(object sender, Access_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Access_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Access_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Access_insertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Access_deleteCompletedEventHandler(object sender, Access_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Access_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Access_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Access_ExistCompletedEventHandler(object sender, Access_ExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Access_ExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Access_ExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void channels_idCompletedEventHandler(object sender, channels_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class channels_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal channels_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591